### PR TITLE
requirements.txt: create file

### PR DESCRIPTION
**Pull request by sbrl**
It is my understanding that you can do `sudo pip3 install -r requirements.txt` to automatically install all the requirements of a project.

This PR creates a `requirements.txt` file for this project.

I hereby release this PR under CC-0 (i.e. the public domain).

### CODE REVIEW

**Comment by jonajames** [comment]
Thank you, this might be very useful expecially in case more dependencies are added in the future

**Comment by sbrl** [comment]
Glad I could be helpful :-)

Can't wait for my first test run of mc2mt to complete! I'm running it with a fairly large map on a Raspberry Pi 4, so it's understandably taking a while :P

I've discovered a number of maps from planetminecraft.com that crash mc2mt, if you're interested too

**Comment by jonajames** [comment]
On a Raspberry it's going to take ages 
:)
Of course I am interested if something is not right! Can you open an issue?

**Comment by sbrl** [comment]
Lol, it did! Just checked it the other day, and it finally finished lol

All the trapdoors & regular doors were the wrong way around, but it was certainly playable.

Sure thing - will do!

Also, I ended up installing the mods required manually, but it would appear mc2mt generates `carpet:wool_COLOURNAME`, whereas the actual name is `carpet:COLOURNAME`.

**Comment by jonajames** [comment]
I know about the trapdoors and doors orientation problem... I tried to figure it out but I don't own a copy of minecraft and it was impossible doing it by hand.

minecraft has three parameters:
facing = NORTH EAST SOUTH WEST
open = true false
hinge = LEFT RIGHT

and these should be converted to minetest wich uses rotation and 2 simmetric doors (a and b)

If you could make sense of wich value goes where the fix is straightforward.

The carpet problem is probably because of a different mod...  I think I used this one
https://github.com/minetest-mods/carpets

**Comment by sbrl** [comment]
Ah, that sounds like a nightmare! I don't own a copy of MC either, so can't help much there :-/

Ah, I see. Perhaps links in the README to the mods in question would help avoid that issue in the future?

**Comment by jonajames** [comment]
That's surely a good idea

**Pull request merged**
